# Generated by Django 4.0.1 on 2022-02-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_agenda_agendaitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'ordering': ['start_time']},
        ),
        migrations.AddConstraint(
            model_name='agendaitem',
            constraint=models.UniqueConstraint(fields=('agenda', 'task'), name='unique_task_for_agenda'),
        ),
    ]
